### ISSUE TITLE
social media icons are not viewable

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymcon_2022_website#13]
colors style needs to be updated

<img width="376" alt="Screen Shot 2022-10-24 at 2 08 03 PM" src="https://user-images.githubusercontent.com/2507232/197595514-80a24a5f-f768-42c6-abf4-4ed25d3f2d45.png">

**Comment by purna135** [comment]
Hi @cuchoi, could you help me in defining the colour theme? We are using the colour code you provided [here](https://github.com/pymc-devs/pymcon_2022/issues/69#issuecomment-1239759095), but we need more colour to make the website look better.

In comparison to the previous colour scheme, some sections of the website are not visible due to the background colour, which we should fix.

Please take a look at both versions of the sites.
- https://purna135.github.io/pymcon-hugo/
- http://pymcon.com/

CC: @canyon289, @mjhajharia what's your thought on this?


I am attaching some screenshots

- Goal section Icon
![image](https://user-images.githubusercontent.com/42216008/198264639-e9ac0231-875c-4d8f-8805-ef5e6b4a6912.png)
 
- Organizer's name and committee not visible:
![image](https://user-images.githubusercontent.com/42216008/198264913-3d9b1aba-b2b5-4b5c-b696-d991015c8061.png)

- The contact form is also not visible
![image](https://user-images.githubusercontent.com/42216008/198265138-a5ce0306-c67e-4791-9013-4901252c4509.png)

**Comment by cuchoi** [comment]
Are colors configured globally or you can choose them for specific sections?

If they can be selected by section, my proposal would be the following (let me know if they make sense to you):
- Use white as the "font" of the icon for the goals (the same as the original website).
- Use #23929e instead of white for the background of the organizers.
- Use #23929e for the background of the contact form fields.

If it can't be selected by section, can you point to where the colors are defined? To check how many colors are needed and see if we can come up with a solution with what we currently have.

**Comment by purna135** [comment]
Thank you, @cuchoi. I will experiment with the color you suggested above and give an update.

> Are colors configured globally or you can choose them for specific sections?

Yes, the colors are set globally as shown below, and we use these color variables in every section. but we can select a different color for each section.
https://github.com/pymc-devs/pymcon_2022_website/blob/481511928dfecb78b662f49585e7034b94b6499b/static/css/main.css#L10-L22
